### ISSUE TITLE
Referencia a Blockly desde el demo: no anda en Firefox

### ISSUE THREAD

**Issue by asanzo** [Program-AR/gs-element-blockly#103]
El demo:

https://program-ar.github.io/gs-element-blockly/

Tiene un error que hace que nada ande:

![seleccion_251](https://user-images.githubusercontent.com/5421992/38310638-7df7a05c-37f3-11e8-9d98-bd25fadd7033.png)

Yo creía que no se podía acceder tan campantemente a Blockly desde ahí. @rodri042 alguna vez anduvo esto?

**Comment by afska** [comment]
A mí me anduvo siempre... y acabo de entrar desde el celu también.

Aunque debo admitir que me faltó probar en Firefox

On Apr 4, 2018 10:33 AM, "asanzo" <notifications@github.com> wrote:

El demo:

https://program-ar.github.io/gs-element-blockly/

Tiene un error que hace que nada ande:

[image: seleccion_251]
<https://user-images.githubusercontent.com/5421992/38310638-7df7a05c-37f3-11e8-9d98-bd25fadd7033.png>

Yo creía que no se podía acceder tan campantemente a Blockly desde ahí.
@rodri042 <https://github.com/rodri042> alguna vez anduvo esto?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Program-AR/gs-element-blockly/issues/103>, or mute the
thread

**Comment by asanzo** [comment]
Exactamente, me acabo de fijar y en Chrome anda, pero en FF no. Qué manía esta de programar sólo pa Chrome, eh XD.

**Comment by afska** [comment]
"se me chispoteó" :P

Hoy más a la noche veo cómo arreglarlo!

On Apr 4, 2018 12:35 PM, "asanzo" <notifications@github.com> wrote:

Exactamente, me acabo de fijar y en Chrome anda, pero en FF no. Qué manía
esta de programar sólo pa Chrome, eh XD.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Program-AR/gs-element-blockly/issues/103#issuecomment-378644165>,
or mute the thread
